server:
  port: 8001
spring:
  application:
    name: product
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848/
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
      url: jdbc:mysql://localhost:3306/product?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true